name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out as much detail as you can — it helps a lot.

  - type: input
    id: version
    attributes:
      label: librarium version
      description: Run `librarium --version` to find out
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      options:
        - npm
        - pnpm
        - yarn
        - Homebrew
        - Standalone binary (install.sh)
        - Built from source
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: How can we reliably reproduce this?
      placeholder: |
        1. Run `librarium run "..." --providers perplexity`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: providers
    attributes:
      label: Which providers are involved?
      multiple: true
      options:
        - perplexity-deep
        - openai-deep
        - gemini-deep
        - perplexity-sonar
        - brave-answers
        - exa
        - brave-search
        - searchapi
        - serpapi
        - tavily
        - Not sure / all
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant output or error messages
      description: Paste any relevant terminal output. Redact API keys.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Config snippet (optional)
      description: Share a relevant excerpt from your `.librarium.json` or `~/.config/librarium/config.json`. Redact API keys.
      render: json
